const MODALS = {
  DOWNLOAD_GROUP: 'DOWNLOAD_GROUP',
  DOWNLOAD_SUBJECT: 'DOWNLOAD_SUBJECT',
  LOADING: 'LOADING',
  LOCKED: 'LOCKED',
  SEARCH: 'SEARCH',
  UNAPPROVED: 'UNAPPROVED'
}

export default MODALS
