name: Deploy ALICE Production

on:
    # Run this workflow on push to production-release tag (via chatops)
    push:
        tags:
          - production-release

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build_production:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_STATIC_SITES }}

    - name: Node.js build
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn build
      env:
        REACT_APP_ENV: production

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ./build/commit_id.txt

    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build/

  deploy:
    name: Deploy Production
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build_production
    with:
      source: 'build'
      target: 'alice.zooniverse.org'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}

  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Deploy Production / deploy_static
      status: ${{ needs.deploy.result }}
      title: 'Alice Production deploy complete'
      title_link: 'https://alice.zooniverse.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
