name: Deploy ALICE Staging

on:
    # Run this workflow on push to master (incl PR merges)
    push:
        branches: [ master ]

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  deploy_staging_branch:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_STATIC_SITES }}

    - name: Node.js build
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn build
      env:
        REACT_APP_ENV: development

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ./build/commit_id.txt

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        creds: ${{ secrets.AZURE_STATIC_SITES }}
        inlineScript: |
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --overwrite \
              --container-name '$web' \
              --name 'preview.zooniverse.org/alice/commit_id.txt' \
              --content-type 'text/plain' \
              --file ./build/commit_id.txt
            rm ./build/commit_id.txt
            az storage blob upload \
              --account-name zooniversestatic \
              --content-cache-control 'public, max-age=60' \
              --overwrite \
              --container-name '$web' \
              --content-type 'text/html' \
              --name 'preview.zooniverse.org/alice/index.html' \
              --file ./build/index.html
            rm ./build/index.html
            az storage blob upload-batch \
              --account-name zooniversestatic \
              --content-cache-control 'public, immutable, max-age=604800' \
              --overwrite \
              --destination '$web/preview.zooniverse.org/alice' \
              --source ./build

    - name: Slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        fields: took
        status: custom
        custom_payload: |
          {
            "channel": "#deploys",
            "icon_emoji": ":octocat:",
            "username": "Deploy Action",
            "attachments": [{
              "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              "mrkdwn_in": ["text"],
              "author_name": "${{ github.actor }}",
              "author_link": "https://github.com/${{ github.actor }}/",
              "author_icon": "https://github.com/${{ github.actor }}.png?size=40",
              "title": "ALICE Staging deploy complete",
              "title_link": "https://alice.preview.zooniverse.org",
              "fields": [
                  {
                      "title": "Status",
                      "value": '${{ job.status }}' === 'success' ? `:white_check_mark: Success in ${process.env.AS_TOOK}` : '${{ job.status }}' === 'failure' ? ':x: Failed' : ':warning: Warning',
                      "short": true
                  },
                  {
                      "title": "Triggered by",
                      "value": "${{ github.event_name }}",
                      "short": true
                  },
                  {
                      "title": "Run Link",
                      "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
              ],
              "thumb_url": "https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png",
              "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}> #${{ github.run_number }}",
              "footer_icon": "https://www.zooniverse.org/favicon.ico"
            }]
          }

# Azure logout
    - name: logout
      run: |
            az logout
