name: Run ALICE Tests

on:
    # Run this workflow on creation (or sync to source branch) of a new pull request
    pull_request:

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Node.js build
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/hydrogen'
        cache: 'yarn'

    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn build
